// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3cFx7mn2yeitudSw9mJL73AdkTGnVnfo',
    appId: '1:118289410253:web:2aadf51379d076f1946184',
    messagingSenderId: '118289410253',
    projectId: 'chat-app-8189a',
    authDomain: 'chat-app-8189a.firebaseapp.com',
    storageBucket: 'chat-app-8189a.firebasestorage.app',
    measurementId: 'G-M5P3462BB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygkZD9bIAZwwPG9wYzzxR7qRGS_I5hCM',
    appId: '1:118289410253:android:7497f37485d39cd3946184',
    messagingSenderId: '118289410253',
    projectId: 'chat-app-8189a',
    storageBucket: 'chat-app-8189a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOp693lRGhh3VTy9iGAwM-BIvkgZbkTxg',
    appId: '1:118289410253:ios:57e5141754b22702946184',
    messagingSenderId: '118289410253',
    projectId: 'chat-app-8189a',
    storageBucket: 'chat-app-8189a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOp693lRGhh3VTy9iGAwM-BIvkgZbkTxg',
    appId: '1:118289410253:ios:57e5141754b22702946184',
    messagingSenderId: '118289410253',
    projectId: 'chat-app-8189a',
    storageBucket: 'chat-app-8189a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3cFx7mn2yeitudSw9mJL73AdkTGnVnfo',
    appId: '1:118289410253:web:1f9c7c5d1f71e98a946184',
    messagingSenderId: '118289410253',
    projectId: 'chat-app-8189a',
    authDomain: 'chat-app-8189a.firebaseapp.com',
    storageBucket: 'chat-app-8189a.firebasestorage.app',
    measurementId: 'G-NPHEEXCT6H',
  );
}
